export const categories = [
  { name: "Electronics", icon: "🖥️" },
  { name: "Fashion", icon: "👗" },
  { name: "Home", icon: "🏡" },
  { name: "Beauty", icon: "💄" },
  { name: "Sports", icon: "⚽" },
  { name: "Books", icon: "📚" },
  { name: "Toys", icon: "🧸" },
  { name: "Automotive", icon: "🚗" },
  { name: "Health", icon: "🩺" },
  { name: "Groceries", icon: "🛒" },
  { name: "Pets", icon: "🐾" },
  { name: "Music", icon: "🎵" },
  { name: "Entreatment", icon: "🎬" },
  { name: "Travel", icon: "✈️" },
  { name: "Gaming", icon: "🎮" },
  { name: "Photography", icon: "📷" },
  { name: "Art", icon: "🎨" },
  { name: "Jewelry", icon: "💍" },
  { name: "Tools", icon: "🔧" },
  { name: "Supplies", icon: "📂" },
  { name: "Kitchenware", icon: "🍴" },
  { name: "Gardening", icon: "🌱" },
  { name: "Stationery", icon: "✏️" },
  { name: "Footwear", icon: "👟" },
];
